import {
  buildSkillMarkdown,
  type ExportPayload,
  type ExportedSkill,
} from "./cookbook-export-client";

export class GitPushError extends Error {
  status: number;
  constructor(message: string, status = 502) {
    super(message);
    this.name = "GitPushError";
    this.status = status;
  }
}

type GitConfig = {
  token: string;
  repo: string;
  baseBranch: string;
  authorName: string;
  authorEmail: string;
};

export type GitPushResult = {
  branch: string;
  prUrl: string;
  prNumber: number;
  commitSha: string;
  fileCount: number;
};

export function loadGitConfig(): GitConfig {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.COOKBOOK_GIT_REPO;
  if (!token) throw new GitPushError("GITHUB_TOKEN not set", 500);
  if (!repo) throw new GitPushError("COOKBOOK_GIT_REPO not set", 500);
  if (!/^[^/]+\/[^/]+$/.test(repo)) {
    throw new GitPushError(
      `COOKBOOK_GIT_REPO must be 'owner/repo', got '${repo}'`,
      500,
    );
  }
  return {
    token,
    repo,
    baseBranch: process.env.COOKBOOK_GIT_BRANCH || "main",
    authorName: process.env.COOKBOOK_GIT_AUTHOR_NAME || "co-os-bot",
    authorEmail:
      process.env.COOKBOOK_GIT_AUTHOR_EMAIL || "co-os-bot@charlieoscar.com",
  };
}

export function branchName(now: Date = new Date()): string {
  const y = now.getUTCFullYear();
  const m = String(now.getUTCMonth() + 1).padStart(2, "0");
  const d = String(now.getUTCDate()).padStart(2, "0");
  const hh = String(now.getUTCHours()).padStart(2, "0");
  const mm = String(now.getUTCMinutes()).padStart(2, "0");
  return `export/${y}-${m}-${d}-${hh}${mm}`;
}

type RepoFile = { path: string; content: string };

function buildFiles(payload: ExportPayload): RepoFile[] {
  const files: RepoFile[] = [
    {
      path: "module.json",
      content: JSON.stringify(payload.module, null, 2) + "\n",
    },
  ];
  for (const skill of payload.skills) {
    files.push({
      path: `skills/${skill.path}`,
      content: buildSkillMarkdown(skill),
    });
  }
  return files;
}

export function buildPrBody(
  payload: ExportPayload,
  triggeredBy: string,
): string {
  const lines: string[] = [
    `Automated export of ${payload.count} skills from the Charlie Oscar Cookbook.`,
    "",
    `- **Triggered by:** ${triggeredBy}`,
    `- **Exported at:** ${payload.exported_at}`,
    "",
    "## Skills",
    "",
  ];
  const sorted = [...payload.skills].sort((a, b) =>
    skillNameOf(a).localeCompare(skillNameOf(b)),
  );
  for (const skill of sorted) {
    const name = skillNameOf(skill);
    lines.push(`- \`${name}\` — ${scopeBadge(skill)}`);
  }
  lines.push("");
  lines.push("_Generated by co-os-bot. Review, then merge to main._");
  return lines.join("\n");
}

function skillNameOf(skill: ExportedSkill): string {
  const fm = skill.frontmatter;
  const n = fm.name;
  if (typeof n === "string") return n;
  return skill.path.replace(/\.md$/, "").split("/").pop() || skill.path;
}

function scopeBadge(skill: ExportedSkill): string {
  const t = skill.frontmatter.scope_type;
  const id = skill.frontmatter.scope_id;
  if (typeof t !== "string") return "?";
  if (t === "global") return "global";
  return `${t}:${typeof id === "string" ? id : "?"}`;
}

async function gh<T>(
  config: GitConfig,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      "User-Agent": "charlie-oscar-os",
    },
    body: body ? JSON.stringify(body) : undefined,
    cache: "no-store",
  });

  if (!res.ok) {
    const text = await res.text();
    throw new GitPushError(
      `GitHub ${method} ${path} failed: ${res.status} ${text.slice(0, 400)}`,
      res.status === 401 || res.status === 403 ? res.status : 502,
    );
  }
  return (await res.json()) as T;
}

export async function pushExportAsPr(
  payload: ExportPayload,
  triggeredBy: string,
  now: Date = new Date(),
): Promise<GitPushResult> {
  const config = loadGitConfig();
  const [owner, repo] = config.repo.split("/");
  const repoPath = `/repos/${owner}/${repo}`;
  const files = buildFiles(payload);
  const branch = branchName(now);

  // 1. Resolve base branch HEAD sha
  const baseRef = await gh<{ object: { sha: string } }>(
    config,
    "GET",
    `${repoPath}/git/ref/heads/${encodeURIComponent(config.baseBranch)}`,
  );
  const baseSha = baseRef.object.sha;

  // 2. Get base commit → base tree sha
  const baseCommit = await gh<{ tree: { sha: string } }>(
    config,
    "GET",
    `${repoPath}/git/commits/${baseSha}`,
  );
  const baseTreeSha = baseCommit.tree.sha;

  // 3. Create a blob for every file
  const blobs = await Promise.all(
    files.map(async (f) => {
      const blob = await gh<{ sha: string }>(
        config,
        "POST",
        `${repoPath}/git/blobs`,
        { content: f.content, encoding: "utf-8" },
      );
      return { path: f.path, sha: blob.sha };
    }),
  );

  // 3b. Identify skills present on base that we no longer have locally → delete them
  const existingTree = await gh<{
    tree: Array<{ path: string; type: string; mode: string }>;
  }>(config, "GET", `${repoPath}/git/trees/${baseTreeSha}?recursive=1`);
  const localPaths = new Set(files.map((f) => f.path));
  const deletions = existingTree.tree
    .filter(
      (e) =>
        e.type === "blob" &&
        e.path.startsWith("skills/") &&
        !localPaths.has(e.path),
    )
    .map((e) => ({
      path: e.path,
      mode: "100644" as const,
      type: "blob" as const,
      sha: null,
    }));

  // 4. Create a new tree off the base tree (additions, modifications, deletions)
  const tree = await gh<{ sha: string }>(
    config,
    "POST",
    `${repoPath}/git/trees`,
    {
      base_tree: baseTreeSha,
      tree: [
        ...blobs.map((b) => ({
          path: b.path,
          mode: "100644",
          type: "blob",
          sha: b.sha,
        })),
        ...deletions,
      ],
    },
  );

  // 5. Create a commit
  const commitMessage = `Cookbook export — ${payload.exported_at} — ${payload.count} skills\n\nTriggered by: ${triggeredBy}`;
  const commit = await gh<{ sha: string }>(
    config,
    "POST",
    `${repoPath}/git/commits`,
    {
      message: commitMessage,
      tree: tree.sha,
      parents: [baseSha],
      author: {
        name: config.authorName,
        email: config.authorEmail,
        date: new Date(now).toISOString(),
      },
      committer: {
        name: config.authorName,
        email: config.authorEmail,
        date: new Date(now).toISOString(),
      },
    },
  );

  // 6. Create the branch ref
  await gh(config, "POST", `${repoPath}/git/refs`, {
    ref: `refs/heads/${branch}`,
    sha: commit.sha,
  });

  // 7. Open the PR
  const prTitleDate = payload.exported_at.slice(0, 10);
  const pr = await gh<{ html_url: string; number: number }>(
    config,
    "POST",
    `${repoPath}/pulls`,
    {
      title: `Cookbook export — ${prTitleDate} — ${payload.count} skills`,
      head: branch,
      base: config.baseBranch,
      body: buildPrBody(payload, triggeredBy),
    },
  );

  return {
    branch,
    prUrl: pr.html_url,
    prNumber: pr.number,
    commitSha: commit.sha,
    fileCount: files.length,
  };
}
